version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
    working_directory: ~/repo
    steps:
      - checkout
      - run:
            name: installing packages
            working_directory: ~/repo/webapp
            command: npm ci
      - run:
            name: building 
            working_directory: ~/repo/webapp
            command: npm run build
workflows:
    build-and-test:
      jobs:
        - build-and-test
